name: Deploy Dev Site

on:
  push:
    branches: 
      - dev
    paths:
      - 'website/website/**'
      - '.github/workflows/firebase.deploy.dev.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: npm install -g firebase-tools

      - run: |
          cd website/website
          # Remove sitemap from dev
          rm -f sitemap.xml
          # Use disallow-all robots
          cp robots.dev.txt robots.txt
          echo "Files in deployment folder:"
          ls -la
          echo "robots.txt content:"
          cat robots.txt

      - run: firebase deploy --only hosting:dev --token "${{ secrets.FIREBASE_DEPLOY_TOKEN }}"
        working-directory: website/website
